---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Weidu.
--- DateTime: 2021/6/2 21:07
---

--- Plugins Info ---
--- @author
--- @version
--- @type string
script_name('Rvanka All')
script_authors('Weidu')
script_version('1.0')
script_description('QQ 487432640')
script_moonloader(26)
--- Plugins Info ---

local events = require("lib.samp.events") --- @Events

local switch = false --- @Bool status

--- @main
function main()
    repeat wait(0) until isSampAvailable()
    wait(2000)
    --- 2秒
    sampRegisterChatCommand('kck', kck)
    sampAddChatMessage('{FF5656}[Rvanka All]: {FFFFFF}加载成功...', -1)
    sampAddChatMessage('{FF5656}[Rvanka All]: {FFFFFF}By Weidu', -1)
    while true do
        wait(0)
    end
end

--- @sampRegisterChatCommand
function kck()
    if isCharOnFoot(PLAYER_PED) then
        --- 判断自己是否在载具中
        return sampAddChatMessage('{FF5656}[Rvanka All]: {FFFFFF}你不在载具上！', -1)
    end
    if switch then
        switch = false
        sampAddChatMessage('{FF5656}[Rvanka All]: {FFFFFF}关闭', -1)
    else
        switch = true
        sampAddChatMessage('{FF5656}[Rvanka All]: {FFFFFF}开启, 长按R', -1)
    end
end

--- @onSendVehicleSync
--- @data
function events.onSendVehicleSync(data)
    if switch then
        local X, Y, Z = getCharCoordinates(PLAYER_PED) --- 获取玩家坐标 @PLAYER_PED
        local result, ped = findAllRandomCharsInSphere(X, Y, Z, 100, true, false) --- 获取半径内的玩家
        local result, show = sampGetPlayerIdByCharHandle(ped)
        if result then
            if isKeyDown(0x52) then --- R
                local angle = getCharHeading(ped)
                pX, pY, pZ = getCharCoordinates(ped)
                data.position.x = pX + 2
                data.position.y = pY - 0.5
                data.position.z = pZ
                data.quaternion[7] = math.random(-100, 100) --- 7-- 7
                data.quaternion[-1] = math.random(-100, 100) --- wtf?! Whistle??
                data.moveSpeed.y = math.random(-100, 100) * math.cos(-math.rad(angle))
                printStringNow('~Y~Rvanka ~B~By Weidu ~R~~>~[ID: ' .. show .. ']~<~', 500)
            end
        end
    end
end
