---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Weidu.
--- DateTime: 2021/6/2 21:07
---

--- Plugins Info ---
script_name('Rvanka All')
script_authors('Weidu')
script_version('1.1')
script_description('QQ: 487432640')
script_moonloader(26)
--- Plugins Info ---

local events = require("lib.samp.events") --- @Events

local switch = false --- @Bool

--- @main
function main()
    repeat wait(0) until isSampAvailable()
    wait(2000)
    --- 2秒
    sampRegisterChatCommand('kck', kck)
    sampAddChatMessage('{F61D00}[{00F8FA}Rvanka All{F61D00}]: {05FB00}加载成功...', -1)
    sampAddChatMessage('{F61D00}[{00F8FA}Rvanka All{F61D00}]: {05FB00}By Weidu', -1)
    while true do
        wait(0)
    end
end

--- @sampRegisterChatCommand
function kck()
    if isCharOnFoot(PLAYER_PED) then
        --- 判断自己是否在载具中
        return sampAddChatMessage('{F61D00}[{00F8FA}Rvanka All{F61D00}]: {F70202}你不在汽车里面！', -1)
    end
    if switch or isCharOnFoot(PLAYER_PED) then
        switch = false
        sampAddChatMessage('{F61D00}[{00F8FA}Rvanka All{F61D00}]: {F70202}关闭', -1)
    else
        switch = true
        sampAddChatMessage('{F61D00}[{00F8FA}Rvanka All{F61D00}]: {05FB00}开启, 长按R', -1)
    end
end

--- @onSendVehicleSync
--- @data
function events.onSendVehicleSync(data)
    if switch then
        for id = 0, sampGetMaxPlayerId(true) do
            if sampIsPlayerConnected(id) then
                local result, ped = sampGetCharHandleBySampPlayerId(id)
                if result then
                    if isKeyDown(0x52) then --- R
                        local maths = getCharHeading(ped)
                        tX, tY, tZ = getCharCoordinates(ped)
                        data.position.x = tX + 2
                        data.position.y = tY - 0.5
                        data.position.z = tZ
                        data.quaternion[7] = math.random(-100, 100) --- 7-- 7
                        data.quaternion[-1] = math.random(-100, 100) --- Bug R人同时 对方会听到你的汽车鸣笛 自己不会有任何听觉效果
                        data.moveSpeed.y = math.random(-100, 100) * math.cos(-math.rad(maths))
                        printStringNow('~Y~Rvanka All~B~By Weidu ~R~~>~[ID: ' .. id .. ']~<~', 1000)
                    end
                end
            end
        end
    end
end
